# Theme Check Configuration
# This file limits the scope to avoid memory issues

root: .

# Ignore large directories and files that might cause memory issues
ignore:
  - node_modules/**
  - .git/**
  - "*.log"
  - "*.tmp"
  - assets/gtranslate-custom.css
  - assets/gtranslate-fixes.css
  - dropdown-diagnostic.js
  - dropdown-test.html
  - navigation-test.html
  - menu-*.js
  - "*.backup.*"
